version: "3.8"

services:
  embedding_pipeline:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    volumes:
      - ./:/app
    command: embedding_pipeline
    restart: unless-stopped
    ports:
      - "8000:8000"

  telegram_bot:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    volumes:
      - ./:/app
    command: telegram_bot
    restart: unless-stopped
