version: "3.8"

services:
  embedding_pipeline:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    volumes:
      - ./user-tweets:/app/user-tweets
      - ./github-repositories:/app/github-repositories
      - ./michael-client.session:/app/michael-client.session
      - ./embeddings.db:/app/embeddings.db
      - ./mimi_config.json:/app/mimi_config.json
    command: embedding_pipeline
    restart: unless-stopped
    ports:
      - "8000:8000"

  telegram_bot:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    volumes:
      - ./embeddings.db:/app/embeddings.db
      - ./mimi_config.json:/app/mimi_config.json
    command: telegram_bot
    restart: unless-stopped
