// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: llm.sql

package persist

import (
	"context"
)

const findChatMessages = `-- name: FindChatMessages :many
SELECT
    messages
FROM
    llm_chat
WHERE
    telegram_peer_id = $1
`

func (q *Queries) FindChatMessages(ctx context.Context, telegramPeerID int64) ([][]byte, error) {
	rows, err := q.db.Query(ctx, findChatMessages, telegramPeerID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items [][]byte
	for rows.Next() {
		var messages []byte
		if err := rows.Scan(&messages); err != nil {
			return nil, err
		}
		items = append(items, messages)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
