// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package persist

import (
	"github.com/jackc/pgx/v5/pgtype"
	"github.com/pgvector/pgvector-go"
)

type Embedding struct {
	ID        pgtype.UUID
	Text      string
	Metadata  []byte
	Embedding pgvector.Vector
}

type TelegramMessage struct {
	PeerID    int64
	Message   string
	CreatedAt pgtype.Timestamptz
}

type TelegramPeer struct {
	ID       int64
	ChatName string
	Enabled  bool
}
