// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package persist

import (
	"github.com/jackc/pgx/v5/pgtype"
	"github.com/pgvector/pgvector-go"
)

type Embedding struct {
	ID        pgtype.UUID
	Text      string
	Metadata  []byte
	Embedding pgvector.Vector
}

type LlmChat struct {
	TelegramPeerID int64
	Messages       []byte
}

type TelegramMessage struct {
	PeerID    int64
	TopicID   pgtype.Int4
	Message   string
	CreatedAt pgtype.Timestamptz
}

type TelegramPeer struct {
	ID       int64
	ChatName string
	Enabled  bool
}

type TelegramTopic struct {
	ID     int32
	PeerID int64
	Title  string
}
