// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package persist

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type GithubRepository struct {
	Owner string
	Name  string
}

type LlmChat struct {
	TelegramID int64
	Messages   []byte
}

type TelegramMessage struct {
	ID        int32
	PeerID    int64
	TopicID   pgtype.Int4
	Message   string
	CreatedAt pgtype.Timestamptz
}

type TelegramPeer struct {
	ID          int64
	ChatName    string
	Description pgtype.Text
	Enabled     bool
}

type TelegramTopic struct {
	ID          int32
	PeerID      int64
	Title       string
	Description string
}
