--
-- Postgres SQL Schema dump automatic generated by geni
--
-- TABLES
CREATE TABLE github_repository (name text NOT NULL, owner text NOT NULL);

CREATE TABLE llm_chat (
    messages jsonb NOT NULL,
    telegram_id bigint NOT NULL
);

CREATE TABLE schema_migrations (id character varying (255) NOT NULL);

CREATE TABLE telegram_message (
    created_at timestamp WITH time zone,
    id integer NOT NULL,
    message text NOT NULL,
    peer_id bigint NOT NULL,
    topic_id integer
);

CREATE TABLE telegram_peer (
    chat_name text NOT NULL,
    description text,
    enabled boolean NOT NULL,
    id bigint NOT NULL
);

CREATE TABLE telegram_topic (
    description text NOT NULL,
    id integer NOT NULL,
    peer_id bigint NOT NULL,
    title text NOT NULL
);

-- CONSTRAINTS
ALTER TABLE
    github_repository
ADD
    CONSTRAINT github_repository_pkey PRIMARY KEY (name);

ALTER TABLE
    github_repository
ADD
    CONSTRAINT github_repository_pkey PRIMARY KEY (owner);

ALTER TABLE
    llm_chat
ADD
    CONSTRAINT llm_chat_pkey PRIMARY KEY (telegram_id);

ALTER TABLE
    schema_migrations
ADD
    CONSTRAINT schema_migrations_pkey PRIMARY KEY (id);

ALTER TABLE
    telegram_message
ADD
    CONSTRAINT telegram_message_peer_id_fkey FOREIGN KEY (peer_id) REFERENCES telegram_peer(id);

ALTER TABLE
    telegram_message
ADD
    CONSTRAINT telegram_message_pkey PRIMARY KEY (id);

ALTER TABLE
    telegram_message
ADD
    CONSTRAINT telegram_message_pkey PRIMARY KEY (peer_id);

ALTER TABLE
    telegram_message
ADD
    CONSTRAINT telegram_message_topic_id_peer_id_fkey FOREIGN KEY (peer_id) REFERENCES telegram_topic(id);

ALTER TABLE
    telegram_message
ADD
    CONSTRAINT telegram_message_topic_id_peer_id_fkey FOREIGN KEY (peer_id) REFERENCES telegram_topic(peer_id);

ALTER TABLE
    telegram_message
ADD
    CONSTRAINT telegram_message_topic_id_peer_id_fkey FOREIGN KEY (topic_id) REFERENCES telegram_topic(id);

ALTER TABLE
    telegram_message
ADD
    CONSTRAINT telegram_message_topic_id_peer_id_fkey FOREIGN KEY (topic_id) REFERENCES telegram_topic(peer_id);

ALTER TABLE
    telegram_peer
ADD
    CONSTRAINT telegram_peer_pkey PRIMARY KEY (id);

ALTER TABLE
    telegram_topic
ADD
    CONSTRAINT telegram_topic_peer_id_fkey FOREIGN KEY (peer_id) REFERENCES telegram_peer(id);

ALTER TABLE
    telegram_topic
ADD
    CONSTRAINT telegram_topic_pkey PRIMARY KEY (id);

ALTER TABLE
    telegram_topic
ADD
    CONSTRAINT telegram_topic_pkey PRIMARY KEY (peer_id);

-- INDEXES
CREATE UNIQUE INDEX github_repository_pkey ON public.github_repository USING btree (owner, name) CREATE UNIQUE INDEX llm_chat_pkey ON public.llm_chat USING btree (telegram_id) CREATE UNIQUE INDEX schema_migrations_pkey ON public.schema_migrations USING btree (id) CREATE UNIQUE INDEX telegram_message_pkey ON public.telegram_message USING btree (id, peer_id) CREATE UNIQUE INDEX telegram_peer_pkey ON public.telegram_peer USING btree (id) CREATE UNIQUE INDEX telegram_topic_pkey ON public.telegram_topic USING btree (id, peer_id)
