// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package persist

import (
	"github.com/jackc/pgx/v5/pgtype"
	"github.com/pgvector/pgvector-go"
)

type Embedding struct {
	ID        pgtype.UUID
	Text      string
	Metadata  []byte
	Embedding pgvector.Vector
}

type TelegramPeer struct {
	PeerID  int64
	Enabled bool
}
